### ISSUE TITLE
Installation issue in v5 parallel

### ISSUE THREAD

**Issue by tribe01** [sundmanbo/opencalphad#33]
I cloned the latest commit and tried to build the parallel version and it looks like one of the files is missing in the GETKEY folder. The error reads as following

`# copy getkey module information
cp utilities/GETKEY/m_getkey.mod .
cp: utilities/GETKEY/m_getkey.mod: No such file or directory
make: *** [metlib3.o] Error 1`

Serial version is building fine without issues. I downloaded the *.zip file of the version5 directly from the website as well and it reproduces the same issue.

**Comment by sundmanbo** [comment]
Dear tribe01

You have to un-comment one line in the Makefile on the GETKEY directory
depending on your Linux dialect.
If you know a way to detect the dialect automatically please let me know.

Best wishes

Bosse


2018-04-25 21:06 GMT+02:00 tribe01 <notifications@github.com>:

**Comment by tribe01** [comment]
Prof.Sundman, Thank you. I have found an ugly way to get around with that by running a bash script inside the Makefile and storing the value as a Make variable. But, I was advised CMake is a robust way to handle this. But, this works. 

Content of the bash script

`unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)     machine=Linux;;
    Darwin*)    machine=Mac;;
    CYGWIN*)    machine=Cygwin;;
    MINGW*)     machine=MinGw;;
    *)          machine="UNKNOWN:${unameOut}"
esac
echo ${machine}`

Modified Makefile
`BJS=getkey.o bintxt.o
EXE=tin
OS = $(shell bash getOS.sh)

all: $(EXE)
getkey.o:
        gcc -c -D$(OS) getkey.c
        gfortran -c M_getkey.F90

bintxt.o:
        gfortran -c bintxt.F90

$(EXE): $(OBJS)
#       gfortran -o $(EXE) testbintxt2.F90 bintxt.o getkey.o

clean:
        rm *.o`
