### ISSUE TITLE
 Can the opencalphad calculate the solidification route of alloys by the Scheil model?

### ISSUE THREAD

**Issue by Selfsong** [sundmanbo/opencalphad#36]
Dear Pro. Sundmando
I am having one question about the software and i want to know if  the opencalphad can calculate the solidification route of alloys by the Scheil model? 
Thanks

**Comment by sundmanbo** [comment]
OC itself has no Scheil simulator (yet) but there is an example of a program written in C++ for Scheil simulation using the OCASI software interface in the directory TQ4lib/Cpp/Scheil/
