### ISSUE TITLE
Gnuplot plotting

### ISSUE THREAD

**Issue by alan1997liu** [sundmanbo/opencalphad#41]
I'm trying to run the macro map1.OCM, and when it tries to plot the phase diagram it's coming back with this error:

set term windows
              ^
line 0: unknown or ambiguous terminal type; type just 'set terminal' for a list

WARNING: error during initialization

set terminal qt size 600,500 font "arial,16"

"ocgnu.plt" line 3: unknown or ambiguous terminal type; type just 'set terminal' for a list

What could be the issue?

**Comment by sundmanbo** [comment]
This is a GNUPLOT error.  Start gnuplot and type "set term" to know which termnal that is installed in your GNUPLOT version.  Then you have to use change your installation of OC and select a windows driver that works, on Linux X11 or aqua are soetimes preferred.  In the Makefile there are some comment lines for the pmon6.o file.  The default there is -Dqtplt, change to -Daqplt or -Dx11.  If you have someting else you have to change the Fortran source code in pmon6.F90 or each time before you plot you can use the command SET GNU and manually enter the gnuplot terminal
