### ISSUE TITLE
Problem with TP functions with real powers, and SOLGASMIX converter

### ISSUE THREAD

**Issue by peymanDavvaloKhongar** [sundmanbo/opencalphad#42]
I have made a database for my work which the TP functions have terms like T**(0.5) "extended Gibbs terms".
I tried to use OC with those terms (without parenthesis and although wrong, with parenthesis) and I got error. I couldn't find it in OC manual but in thermocalc database manual (which is similar used in OC), it is mentioned:
` Page 13, Section 3.14, Paragraph 2, Thermo-Calc Database Guide: The expression is a FORTRAN-like expression and operators +, -, *, = and ** can be used (** only with integer powers)..`
I tried to work around it to use EXP and LN combined: `EXP(LN(0.5*T))` 
OC does not provide any error message while reading the TDB file and accept it, however, using oc5p, I set t=1000 and using CALCULATE, I calculated TP functions including the term, which gives wrong result.
I am wondering if OC is capable of receiving term like T**(0.5) or if it is possible to extend the integer capability of power to accept real numbers in parenthesis as well. if not possible, I would be grateful if you provide me a suggest to work around it.

Another point is that if I made a dummy case using a term of EXP(T) in a TP function and convert the TDB file to DAT file, and it will write:
`Ag
 4  1     1.00    0.00
   3000.0000   0.0000000       0.0000000       0.0000000       0.0000000       0.0000000       0.0000000    
  1   1.0   0.50`
The last line refers to 1 extra term, with coefficient of 1.0 and power of 0.5.(basicly T**(0.5)) which is not correct.

**Comment by peymanDavvaloKhongar** [comment]
I have solved the first issue by doing this:
I have defined a dummy function "TMP" and used it in actual function.
`FUNCTION TMP    298.15   +0.5*LN(T); 3000 N !   `
` FUNCTION GHSERAG   298.15  EXP(TES#); 3000 N !`
`.`
`.`
`.`
`PARAMETER G(LIQUID,AG;0) 298.15    +GHSERAG#;  3000  N   !`
Using CALCULATE  both function value and its derivate are now correct but still the converted DAT file gives wrong result:
`Ag`
 `4  1     1.00    0.00`
  ` 3000.0000  0.50000000       1.0000000       0.0000000       0.0000000       0.0000000       0.0000000    `
  `1   1.0000000       0.50` 
which means:
`G(LIQUID,AG;0) = 0.5+T+T**(0.5)`

**Comment by sundmanbo** [comment]
Hi, the TP functions are quite fragile by themselves and converting to DAT files is quite a mess.  I will have a look at conversion of T**(0.5).  Try to use the functions
FUNCTION HALF1 298.15 0.5 * LN(T); ,,,,,
FUNCTION HALF2 298.15 EXP(HALF1);,,,,,,
FUNCTION GHSERAG 298.15 1 * HALF2; ,,,,,

You can contact me directly by email, I do not login at github very often.

**Comment by sundmanbo** [comment]
Hi again, I have found and fixed this problem but most likely there will be other problems with FUNCTIONS both in OC and when converting to DAT files.  Keep the functions simple and avoid adding functions with different temperature ranges.

**Comment by sundmanbo** [comment]
PS, wait for the next update on github.
