### ISSUE TITLE
Error 4244 at peritectic reaction

### ISSUE THREAD

**Issue by nitride84** [sundmanbo/opencalphad#43]
I have been having error 4244 at peritectic reactions when using cost507R.tdb to calculate aluminum alloys.    The error is not limited to Al-Zr alloys and the following script will reproduce my error message:
=================================

r t cost507R
Al Zr

set c w%(Zr)=0.3 t=800 p=1e5 n=1
c e
l,,,
set axis 1 t 500 1000 5
step normal

======================================

I get error after the stepping.  The message is below:
==========================================
Line   1 from   8.000000E+02 with: AL3ZR1 FCC_A1
 SMP2 Successful calculation of a node point           1
Creating node where a new phase LIQUID becomes stable
Finishing line with    33 equilibria at T=  933.83

Line   2 from   8.000000E+02 with: AL3ZR1 FCC_A1
Terminating line with   46 equilibria at axis limit   6.0000E+02

Line   3 from   9.338849E+02 with: LIQUID AL3ZR1 FCC_A1
MM Phase change not allowed: -FCC_A1
MM Phase change not allowed: -FCC_A1
MM Phase change not allowed: -FCC_A1
Terminating line with    0 equilibria at   6.0000E+02 due to error 4244
Finished step/map   9.4000E-02 s and     105 clockcycles

===============================================

**Comment by sundmanbo** [comment]
Hi

As is written when you STEP or MAP this is fragile and I appreciate to have feedback of problems. 
You have hit on a problem I know but I have not had time to fix.  What happens at 933.83 K is that the STEP finds an invariant with 3 phase in equilibrium and I have not implemented how STEP should handle that.  Basically it is trivial but I have just 24 hours/day and 7 dats/week to fix everything.  The simplest remedy for you is to set a new startpoint maybe at 1000 K and give a new STEP command (and not reinitiate).  After that you can plot the whole T range.

OC works normally better when you have more components, in binaries there are a lot of invariant equilibria, less so when you have 6 or more components.

Best wishes

Bo Sundman

**Comment by sundmanbo** [comment]
Hi again

Thanks to your question I have fixed the problem passing an invariant equilibria during STEP.  The version I uploaded here yesterday (or the Windows version at opencalphad.org) should now manage invariant equilibria (but may still need several startpoint for other reasons).

Best wishes

Bosse
