### ISSUE TITLE
Modeling ordered phases with more then 1 interstitial sublattice

### ISSUE THREAD

**Issue by Ebert-Daniel** [sundmanbo/opencalphad#45]
Hello Professor Bo,

I'm interested on modeling an ordered phase which interstitial sites can be occupied. It turns out that when the ordered phase is formed, we have 2 distinct octahedral interstitial sites. I would like to compute these differences. When I tried entering this on TC, the following message appeared:

*** ERROR  1181 IN GZDIS2: INCONSISTENT NUMBER OF SUBLATTICES
 The database violates some of these checks:

 *** BEWARE, minimal checks are made that you use this command correctly
 Requirements are:

1. The disordered phase (DP) should have max two sublattices.
2. The ordered phase (OP) should have at least one more sublattice.
3. If the DP has two sublattices the last sublattice for both phases should be for the same "interstitial" constituents.
4. The ratio between the substitutional and interstital sublattice for DP must be the same as the ratio between the sum of all ordering sublattices for OP and the interstitial sublattice.
5. The first (or only) sublattice for the DP represent a substitutional mixing of all constituents on all ordering sublattices of the OP.
6. Normally the constituents on all ordering sublattices in the OP are identical to those on the first sublattice of the DP.
It is allowed that some constituents do not enter all sublattices in the OP.
7. The Gibbs energy (and all first and second partial derivatives) for OP and DP (multiplied with the site ratio) will be added together. (Ignoring the config. entropy for DP). If you read from a database the type definitions may have to be rearranged for the phases BCC_B2 and BCC_A2
Type definitions are executed in the order they appear. ERROR 1181 RESET

Is it possible to do it with OC? Could you please point me in the right direction on the source code?

Thank you very much

EA

**Comment by sundmanbo** [comment]
I have no idea how TC works today, I have not seen the code for 10 years although I think the error message you got is something I wrote more than 10 years ago.
This error you get is when you try to enter a disordered fraction set.  There is no need to have a disordered fraction set to model ordering although it may be useful. 
In principle there is no problem having two or more additional sublattices which are not included in the ordering but as it is rare it may not work even with OC.  My proposal is that you try to model the ordering without using the disordered fraction set.  I
If you have further questions using OC please email me directly

**Comment by sundmanbo** [comment]
You can easily find my email on internet
