### ISSUE TITLE
Mapping problems

### ISSUE THREAD

**Issue by Ebert-Daniel** [sundmanbo/opencalphad#46]
Hello dear Professor Bo Sundman,

I'm having problems to plot a simple binary diagram. I've confirmed that the Gibbs energy of the phases are the same as when I plot the same diagram using other thermodynamic software. Here attached you may find OpenCalphad macro files for reproducing this. Would you have any advice for plotting this diagram or correcting the setup_OCM? 

Thank you very much for supporting thermodynamic research!

[f_FeTi_OCM.txt](https://github.com/sundmanbo/opencalphad/files/5390172/f_FeTi_OCM.txt)
[gibbs_plt_OCM.txt](https://github.com/sundmanbo/opencalphad/files/5390180/gibbs_plt_OCM.txt)
[map_OCM.txt](https://github.com/sundmanbo/opencalphad/files/5390181/map_OCM.txt)
[Ukita_TDB.txt](https://github.com/sundmanbo/opencalphad/files/5390184/Ukita_TDB.txt)

![Gibbs-500_OC](https://user-images.githubusercontent.com/54397165/96234368-a0f8b980-0f99-11eb-9bcf-7cbd731aad6d.png)
![Gibbs-500](https://user-images.githubusercontent.com/54397165/96234382-a524d700-0f99-11eb-933e-b91a4f22dd9b.png)
![Ti-H - Diagram_OC](https://user-images.githubusercontent.com/54397165/96234595-ec12cc80-0f99-11eb-9da5-29b3f9887596.png)
![Ti-H - Diagram](https://user-images.githubusercontent.com/54397165/96234346-9c340580-0f99-11eb-9cc4-6a31d3311845.png)

**Comment by sundmanbo** [comment]
Please contact me by email for this type of questions, it is mainly a database issue
I am looking at it but the description of the Ti-H system is very strange, where is the gas phase?
