### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Ebert-Daniel** [sundmanbo/opencalphad#47]
Hello dear Prof. Bo Sundman

I'm trying to assess a ternary system which includes a ternary Ord-Dis bcc phase and some quasi-stoichiometric phases which have only solubility in interstitial sublattices of interstitial atoms. I had the following error message:

```
Warning: global minimizer cannot be used for the current set of conditions
Phase change (equil:  19) iteration:    18, phase: -BCC#1
Phase change (equil:  19) iteration:    22, phase: -BCC_AUTO#3
Phase change (equil:  19) iteration:    26, phase: +BCC#1
Phase change (equil:  19) iteration:    33, phase: +BCC_AUTO#3
Phase change (equil:  19) iteration:    37, phase: -BCC#1
Phase change (equil:  19) iteration:    38, phase: +BCC#1
Phase change (equil:  19) iteration:    42, phase: -BCC#1
Phase change (equil:  19) iteration:    44, phase: +BCC#1
Phase change (equil:  19) iteration:    48, phase: -BCC#1
Phase change (equil:  19) iteration:    54, phase: +BCC#1
Phase change (equil:  19) iteration:    58, phase: -BCC#1
Phase change (equil:  19) iteration:    62, phase: -BCC_AUTO#3
Phase change (equil:  19) iteration:    66, phase: +BCC#1
Phase change (equil:  19) iteration:    73, phase: -BCC#1
Phase change (equil:  19) iteration:    81, phase: +BCC_AUTO#3
Phase change (equil:  19) iteration:    85, phase: -BCC_AUTO#3
Phase change (equil:  19) iteration:    87, phase: +BCC_AUTO#3
Phase change (equil:  19) iteration:    91, phase: -BCC_AUTO#3
MM Removing phase:    1   2#1
MM Restoring phase:      1    2  BCC#1
Equilibrium result:  120 its,   3.6431E-02 s,     37 cc, GS= -5.4731928E+04 J/mol
Testing if any gridpoint is below the calculated equilibrium
 3Y could not find gridpoint          683  in phase            2         324
 3Y Failed extract constitution  -219579474
 3Y Equilibrium wrong, gridtest found BCC                     
 3B creates a composition set in all equilibria

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7f44f2d1832a
#1  0x7f44f2d17503
#2  0x7f44f1f4703f
#3  0x55bed148eed4
#4  0x55bed14f2647
#5  0x55bed15206b6
#6  0x55bed138d23e
#7  0x55bed1379ddc
#8  0x55bed1379bae
#9  0x7f44f1f29bf6
#10  0x55bed1379be9
#11  0xffffffffffffffff
Segmentation fault (core dumped)
```
I entered "many_equilibria" . All the equilibria are similiar and most of them cannot be calculated. Some of them show this kind of error and OC crashes.

Would you mind helping me using OC to parametrize these phases?

Thank you very much
Best regards

**Comment by Ebert-Daniel** [comment]
Hello again Professor,

To be more precise, I'm having difficulties to calculate "step separate" when applying x(A)-x(B)=0 conditions. It seems to create a extra new "x(A)-x(B)=0" condition after I "step sep" and got the error. Even when I set level to advanced and change the BIT to not allow minimization. I also tried to set the grid density to "Very dense grid".
Specially for a 4 sublattice phase with solubility in the 2 last sublattices, I cannot even start the calculation. It has a miscibility gap due to interactions of two atoms in the last sublattice but I don't know if this is the problem.

Sorry for so many questions. I would very much appreciate to share the files with you by email. 
Thank you again for your patience

Best wishes
Ebert

**Comment by sundmanbo** [comment]
Please send me the files by email, I have noticed the problem with conditions that are expressions but I have not had time to fix it and it is not used very much.

**Comment by sundmanbo** [comment]
I have updated the github version fixing the problem with condition x(a)-x(b)
If you have other problems please contact me directly by email

**Comment by sundmanbo** [comment]
I hope it works now
