### ISSUE TITLE
fpm support

### ISSUE THREAD

**Issue by epagone** [sundmanbo/opencalphad#49]
Is there any interest in supporting the [official Fortran Package Manager (fpm)](https://github.com/fortran-lang/fpm/) that would make building and distributing OpenCalphad cross-platform much simpler?

**Comment by CINTROINI** [comment]
What are the differences with GNU autotools, Spack, or other tools commonly used to build, manage and package source code?

**Comment by epagone** [comment]
Compared to autotools is much less complex to use and it should work much more nicely cross-platform. Compared to Spack or Conda, the advantage is that it's Fortran-centric and it should require much less effort to package a Fortran library or app.

**Comment by sundmanbo** [comment]
I am developing OpenCalphad for my own pleasure, I try to provide a Makefile that whould work on non-Windows systems but I do not understand much of that.   I am not interested to learn specific tools and I have no funding for this work.

**Comment by epagone** [comment]
fpm allows to maintain packages for all operating systems (non-Windows systems included) relieving the burden to develop and maintain complex Makefiles (saving time and money and allowing to focus on the development of the package). It is exactly your use case. It is free, there is no funding to be raise for that.

**Comment by sundmanbo** [comment]
I am sorry but I detest all kinds of tools that try to hide away the messy file structures for my program  I prefer to copy files manually and change directories whenever necessary.  I detest the github GUI that I am now forced to use to update the files, I have no idea what is the master and never use tags or whatever it is called.  Maybe if I was younger I would like them.
