### ISSUE TITLE
start.OCM causes crash

### ISSUE THREAD

**Issue by tagMacher** [sundmanbo/opencalphad#51]
Ubuntu Linux 18.04 LTS, openCalphad v 6.001
**Question**: Is there a specific text format and encoding to be used for the `start.OCM` file? Having a `start.OCM` file in the `OCHOME` path causes oc6 to crash.
**Doing this**: I need to change the default gnuplot terminal on each run of oc6P. I have tried putting this into a start.OCM file with the following single line that works on the oc6 command prompt:
`enter gnuplot SCREEN x11 size 768,640 font "Arial,16"`  
However, next start of oc6 results in a crash:
**Details**: 
`divakar@divakar:~/dev/oc/opencalphad-v.6.0$ ./oc6P

Open Calphad (OC) software version   6.001 , linked 2021-10-25
with command line monitor version 55

This program is available with a GNU General Public License.
either version 2 of the License, or any later version.
It includes the General Thermodynamic Package, version GTP-3.30,
Hillert's equilibrium calculation algorithm version HMS-3.0 ,
step/map/plot software version SMP-2.30 using GNUPLOT 5.0 graphics.
Numerical routines are extracted from LAPACK and BLAS and
the assessment procedure uses LMDIF from ANL.

Linked with OpenMp for parallel execution
 Found OC home directory (OCHOME): /home/divakar/dev/oc
 Online help provided by your browser using ochelp.html
 Reading your startup macro: /home/divakar/dev/oc/start.OCM
 Working directory is: /home/divakar/dev/oc/opencalphad-v.6.0
--->OC6:GNUPLOT terminals are: 5
    Name     > command      GNUPLOT options
 1  SCREEN   > set terminal qt size 600,500 font "Arial,16"
 2  PS       > set terminal postscript color solid fontscale 1.2
 3  PDF      > set terminal pdf color solid size 6,5 enhanced font "Arial,16"
 4  GIF      > set terminal gif enhanced fontscale 0.7
 5  PNG      > set terminal png enhanced fontscale 0.7
Change (exact match required) or enter a new GNUPLOT termial
 Modifying terminal SCREEN  
New terminal definition for plot 
 1  SCREEN  set terminal x11 size 768,640 font "Arial,16"
    with file extention: 
--->OC6:--->OC6:--->OC6:--->OC6:--->OC6:--->OC6:--->OC6:--->OC6:--->OC6:At line 4169 of file utilities/metlib4.F90 (unit = 50, file = '/home/divakar/dev/oc/start.OCM')
Fortran runtime error: End of file

Error termination. Backtrace:
#0  0x7efecb31b32a
#1  0x7efecb31bed5
#2  0x7efecb31c69d
#3  0x7efecb492ca3
#4  0x7efecb49328a
#5  0x7efecb48fe8f
#6  0x7efecb49479c
#7  0x7efecb49572c
#8  0x555c4ec8f95e
#9  0x555c4ec9a1f2
#10  0x555c4ec9b7b9
#11  0x555c4ec9ca15
#12  0x555c4ee0483f
#13  0x555c4ec7de44
#14  0x555c4ec7db5e
#15  0x7efeca52cbf6
#16  0x555c4ec7db99
#17  0xffffffffffffffff
`
Even having a blank zero byte start.OCM file causes oc6 to fail with `--->OC6:At line 4169 of file utilities/metlib4.F90 (unit = 50, file = '/home/divakar/dev/oc/start.OCM')
Fortran runtime error: End of file`

**Comment by sundmanbo** [comment]
Where did you fiind version 6.001 of OC?
Current version is 6.035

I cannot fix problems with earlier versions and testing with 6.035 is no problems
Additionally there is no real need to define gnuplot terminal, plotting on screen
the gnuplot windows provides several option for hardcopy terminals

**Comment by sundmanbo** [comment]
Sorry I did not see this issue earlier

**Comment by tagMacher** [comment]
Thanks, will try code from github repository.  
Source code OC6-stable.zip is available at http://www.opencalphad.org/;  this is where I got 6.001. Compiling from the OC6-stable.zip downloaded today from http://www.opencalphad.com/downloads/oc6-stable.zip gives version as 6.004:
`Open Calphad (OC) software version   6.004 , linked 2021-11-13  
with command line monitor version 55  
`

**Comment by sundmanbo** [comment]
I am sorry, I was sure it was updated this summer.  I will try to update.
Do not bother with the start file.


Den lör 13 nov. 2021 kl 12:05 skrev tagMacher ***@***.***>:

**Comment by sundmanbo** [comment]
Maybe you should install OC-CAE, I think that uses a later version of OC
and it has a graphical user interface that is so popular today.
There is a link at the bottom of the OC home page

Best wishes

Bosse


Den lör 13 nov. 2021 kl 12:20 skrev Bo Sundman ***@***.***>:

**Comment by tagMacher** [comment]
Thanks, again. 6.035 from the github repository is fine. This version works without the need to redefine gnuplot settings on my home computer - will check tomorrow on work machine. As far as I can see OC-CAE is for windows which I do not use. 
Regards,
Divakar

**Comment by sundmanbo** [comment]
OK, I had assumed you downloaded the precompiled Windows version,
if you compile OC yourself please use the github version.

Best wishes

Bosse


Den sön 14 nov. 2021 kl 11:39 skrev tagMacher ***@***.***>:
