### ISSUE TITLE
Too complicated TP function term 

### ISSUE THREAD

**Issue by broshe** [sundmanbo/opencalphad#52]
I was trying to read the attached TDB file:
[Fe-C_Fei_Brosh_2014_09.TDB.txt](https://github.com/sundmanbo/opencalphad/files/9667854/Fe-C_Fei_Brosh_2014_09.TDB.txt)
I got the error message "Too complicated TP function term".
Thermo-calc does read the file. Can this be fixed?

Eli

**Comment by sundmanbo** [comment]
If you can use it with Thermo-Calc I do not think I need to do anything.
