### ISSUE TITLE
Identifiers or acronyms

### ISSUE THREAD

**Issue by Trianex** [sundmanbo/opencalphad#55]
Dear All,
Is there any reference material related with OpenCalphad to check the identifiers or acronyms?
For instance:
FCC-A1# (I know just FCC: face-centered cubic)
FCC-A1-AUTO#2
NP
and etc.

**Comment by gongyilun** [comment]
check Strukturbericht designation on Wikipedia.  -Yilun

**Comment by Trianex** [comment]
Hi Yilun,
Thank you.

All the best,
Trianex

**Comment by Trianex** [comment]
Hi Yilun,
Thank you.

All the best,
Trianex
