### ISSUE TITLE
ModuleNotFoundError: No module named 'rawpyOC'

### ISSUE THREAD

**Issue by Arosyisagoodcivilizen** [sundmanbo/opencalphad#57]
hi there，running the example in pyoc reports an error ModuleNotFoundError: No module named 'rawpyOC'
how to dissolve it.

**Comment by CINTROINI** [comment]
Hi, 

you need to install f90wrap and f2py-f90wrap on your laptop. 

How to you install OC ? Linux? 

The pyOC version available in the repository is old. An update could be done later with a more advanced Python interface . 
Contact me directly if you are interested in. 

CI

**Comment by Arosyisagoodcivilizen** [comment]
> Hi,
> 
> you need to install f90wrap and f2py-f90wrap on your laptop.
> 
> How do you install OC ? Linux?
> 
> The pyOC version available in the repository is old. An update could be done later with a more advanced Python interface . Contact me directly if you are interested in.
> hou could I get it，please
> CI

**Comment by namhgoo142** [comment]
> Hi,
> 
> you need to install f90wrap and f2py-f90wrap on your laptop.
> 
> How do you install OC ? Linux?
> 
> The pyOC version available in the repository is old. An update could be done later with a more advanced Python interface . Contact me directly if you are interested in.
> 
> CI

Can I generate the rawpyOC module by the compiling of pyOC.f90 file ?

**Comment by sundmanbo** [comment]
There is currently no support for Python with OC.  Too many other things to do
