### ISSUE TITLE
How to Modify the Fixed Size of the Results Window in OpenCalphad?

### ISSUE THREAD

**Issue by liulizhen-boop** [sundmanbo/opencalphad#59]
Hi, I'm currently using OpenCalphad for my thermodynamic calculations, and I've encountered an issue with the GUI.

The results window within the main interface appears to be fixed in size, and I'm unable to resize it. While I can adjust the size of other windows or panels, such as the TEXT editor and log information panels, the results window does not respond to attempts to resize it.

I’ve tried modifying the startup_window_resolution_height and startup_window_resolution_width settings in the settings.ini file, but this doesn’t seem to affect the results window specifically. I also explored the idea that there might be a configuration file in the installation directory that controls the layout or window behavior, but I couldn't find anything that worked.

Is there any way to enable resizing for the results window, or is this a known limitation in the current version of OpenCalphad? Any advice or workarounds would be greatly appreciated.

Thanks in advance for your help!

**Comment by sundmanbo** [comment]
OC has minimal graphics but it generates an GNUPLOT text file (normally called ocgnu.plt)
and inside this one can change size of this.  One just has to learn GNUPLOT
